apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Service
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-deployment
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: nginx-deployment
        image: yassminabubakr/capstone_helloworld2
        ports:
        - containerPort: 80
