apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
  labels:
    app: nginx-deployment
spec:
  type: LoadBalancer
  selector:
    app: nginx-deployment
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-deployment
  namespace: default  
spec:
  selector:
    matchLabels:
      app: nginx-deployment
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: nginx-deployment
        image: yassminabubakr/capstone_helloworld
        ports:
        - containerPort: 80

